### ISSUE TITLE
Crash with example code

### ISSUE THREAD

**Issue by taljaards** [NOVAAPI/NovaExample#27]
I've downloaded the entire repo to inspect an example of how to start off.

I ran `gradlew block:runClient`

After downloading, it crashes:

```
[21:10:58] [main/INFO]: Extra: []
[21:10:58] [main/INFO]: Found and added coremod: nova.wrapper.mc1710.NovaMinecraftCore
[21:10:58] [main/INFO]: Running with arguments: [--userProperties, {}, --assetsDir, C:/Users/Stephan Taljaard/.gradle/caches/minecraft/assets, --assetIndex, 1.7.10, --accessToken, {REDACTED}, --version, 1.7.10, --tweakClass, cpw.mods.fml.common.launcher.FMLTweaker, --tweakClass, net.minecraftforge.gradle.tweakers.CoremodTweaker]
[21:10:58] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[21:10:58] [main/INFO]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[21:10:58] [main/INFO]: Loading tweak class name net.minecraftforge.gradle.tweakers.CoremodTweaker
[21:10:58] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[21:10:58] [main/INFO]: Forge Mod Loader version 7.10.88.1300 for Minecraft 1.7.10 loading
[21:10:58] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_31, running on Windows 8.1:amd64:6.3, installed at C:\Program Files\Java\jdk1.8.0_31\jre
[21:10:58] [main/INFO]: Managed to load a deobfuscated Minecraft name- we are in a deobfuscated environment. Skipping runtime deobfuscation
[21:10:58] [main/INFO]: Found a command line coremod : nova.wrapper.mc1710.NovaMinecraftCore
[21:10:58] [main/INFO]: Calling tweak class net.minecraftforge.gradle.tweakers.CoremodTweaker
[21:10:58] [main/INFO]: Injecting location in coremod cpw.mods.fml.relauncher.FMLCorePlugin
[21:10:58] [main/INFO]: Injecting location in coremod net.minecraftforge.classloading.FMLForgePlugin
[21:10:58] [main/INFO]: Injecting location in coremod nova.wrapper.mc1710.NovaMinecraftCore
[21:10:58] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:10:58] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[21:10:58] [main/INFO]: Loading tweak class name net.minecraftforge.gradle.tweakers.AccessTransformerTweaker
[21:10:58] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:10:58] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:10:58] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:10:58] [main/ERROR]: The binary patch set is missing. Either you are in a development environment, or things are not going to work!
[21:10:59] [main/ERROR]: FML appears to be missing any signature data. This is not a good thing
[21:10:59] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:10:59] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:10:59] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
[21:11:00] [main/INFO]: Calling tweak class net.minecraftforge.gradle.tweakers.AccessTransformerTweaker
[21:11:00] [main/INFO]: Remapping AccessTransformer rules...
[21:11:00] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.TerminalTweaker
[21:11:00] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker
[21:11:00] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[21:11:00] [main/INFO]: Setting user: Player328
[21:11:01] [main/INFO]: [nova.wrapper.mc1710.asm.transformers.TileEntityTransformer:transform:13]: [NOVA] Transforming TileEntity class for dynamic instance injection.
[21:11:01] [main/INFO]: [nova.wrapper.mc1710.asm.transformers.TileEntityTransformer:transform:21]: [NOVA] Lookup [aor.c(Ldh;)Laor;] failed. You are probably in a deobf environment.
[21:11:01] [main/INFO]: [nova.wrapper.mc1710.asm.transformers.TileEntityTransformer:transform:29]: [NOVA] Transforming method createAndLoadEntity
[21:11:02] [Client thread/INFO]: LWJGL Version: 2.9.1
[21:11:03] [Client thread/INFO]: Attempting early MinecraftForge initialization
[21:11:03] [Client thread/INFO]: MinecraftForge v10.13.2.1300 Initialized
[21:11:03] [Client thread/INFO]: Replaced 183 ore recipies
[21:11:03] [Client thread/INFO]: Completed early MinecraftForge initialization
[21:11:03] [Client thread/INFO]: Searching C:\Downloads\NOVA-Example-master\NOVA-Example-master\block\run\mods for mods
[21:11:06] [Client thread/INFO]: Forge Mod Loader has identified 5 mods to load
[21:11:07] [Client thread/INFO]: Attempting connection with missing mods [mcp, FML, Forge, novapreloader, nova] at CLIENT
[21:11:07] [Client thread/INFO]: Attempting connection with missing mods [mcp, FML, Forge, novapreloader, nova] at SERVER
[21:11:07] [Client thread/INFO]: [nova.wrapper.mc1710.NovaMinecraftPreloader:load:74]: Successfully hacked 'org.apache' out of launcher exclusion
[21:11:07] [Client thread/INFO]: [nova.wrapper.mc1710.NovaMinecraftPreloader:lambda$registerResourcePacks$5:151]: Registered NOVA jar resource pack: file:/C:/Downloads/NOVA-Example-master/NOVA-Example-master/block/build/libs/block-0.1.jar
[21:11:07] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:NOVA, block-0.1.jar
[21:11:07] [Client thread/WARN]: Unable to parse metadata section of resourcepack: block-0.1.jar
net.minecraft.client.resources.ResourcePackFileNotFoundException: 'pack.mcmeta' in ResourcePack 'C:\Downloads\NOVA-Example-master\NOVA-Example-master\block\build\libs\block-0.1.jar'
    at net.minecraft.client.resources.FileResourcePack.getInputStreamByName(SourceFile:40) ~[FileResourcePack.class:?]
    at net.minecraft.client.resources.AbstractResourcePack.getPackMetadata(SourceFile:55) ~[AbstractResourcePack.class:?]
    at net.minecraft.client.resources.LanguageManager.parseLanguageMetadata(LanguageManager.java:50) [LanguageManager.class:?]
    at net.minecraft.client.Minecraft.refreshResources(Minecraft.java:611) [Minecraft.class:?]
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:234) [FMLClientHandler.class:?]
    at net.minecraft.client.Minecraft.startGame(Minecraft.java:480) [Minecraft.class:?]
    at net.minecraft.client.Minecraft.run(Minecraft.java:867) [Minecraft.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_31]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_31]
    at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_31]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
    at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source) [start/:?]
    at GradleStart.main(Unknown Source) [start/:?]
[21:11:07] [Client thread/INFO]: Processing ObjectHolder annotations
[21:11:07] [Client thread/INFO]: Found 341 ObjectHolder annotations
[21:11:07] [Client thread/INFO]: Configured a dormant chunk cache size of 0
[21:11:08] [Client thread/INFO]: Applying holder lookups
[21:11:08] [Client thread/INFO]: Holder lookups applied
[21:11:08] [Client thread/ERROR]: Fatal errors were detected during the transition from PREINITIALIZATION to INITIALIZATION. Loading cannot continue
[21:11:08] [Client thread/INFO]: [net.minecraft.client.Minecraft:displayCrashReport:349]: ---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 2015/07/12 9:11 PM
Description: Initializing game

java.lang.NullPointerException: Initializing game
    at cpw.mods.fml.common.LoadController.printModStates(LoadController.java:267)
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:131)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:515)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239)
    at net.minecraft.client.Minecraft.startGame(Minecraft.java:480)
    at net.minecraft.client.Minecraft.run(Minecraft.java:867)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source)
    at GradleStart.main(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at cpw.mods.fml.common.LoadController.printModStates(LoadController.java:267)
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:131)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:515)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239)
    at net.minecraft.client.Minecraft.startGame(Minecraft.java:480)

-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.Minecraft.run(Minecraft.java:867)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source)
    at GradleStart.main(Unknown Source)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_31, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 262922952 bytes (250 MB) / 349700096 bytes (333 MB) up to 1895825408 bytes (1808 MB)
    JVM Flags: 0 total; 
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: ~~ERROR~~ NullPointerException: null
    Launched Version: 1.7.10
    LWJGL: 2.9.1
    OpenGL: GeForce GT 555M/PCIe/SSE2 GL version 4.5.0 NVIDIA 350.12, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Packs: []
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Anisotropic Filtering: Off (1)
[21:11:08] [Client thread/INFO]: [net.minecraft.client.Minecraft:displayCrashReport:359]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Downloads\NOVA-Example-master\NOVA-Example-master\block\run\.\crash-reports\crash-2015-07-12_21.11.08-client.txt

```

**Comment by taljaards** [comment]
Related to #14?

**Comment by RX14** [comment]
While I cannot reproduce this error while running NOVA from IDEA, it can be reproduced by running `gradle block:runClient`. Attaching a debugger to this yields the stacktrace http://hastebin.com/ezumiziyel.txt

DOWN WITH EXCEPTION EATING

**Comment by taljaards** [comment]
Well, now that you've mentioned running from IDEA, I ran `gradle block:runClient` in a cmd only, if that makes a difference...

**Comment by calclavia** [comment]
This is the error: 

```
net.minecraft.client.resources.ResourcePackFileNotFoundException: 'pack.mcmeta' in ResourcePack 'C:\Downloads\NOVA-Example-master\NOVA-Example-master\block\build\libs\block-0.1.jar'
```

We have to include pack.mcmeta virtually into the mod's resource, or at least have NOVA "fake the JSON into the system".

Does this happen both on MC 1.7 and 1.8?

**Comment by RX14** [comment]
No. I made a pack.mcmeta and it was the same crash. This is unrelated.

**Comment by magik6k** [comment]
It happens to me when I try to use gradle to launch an empty example(worldgen). I'll try to port the whole thing to nova-gradle and see if it helps.

**Comment by Kubuxu** [comment]
I had the same problem. It was due to binary incompatibility of wrapper and core. I don't know why it wouldn't refresh. We need to implement SemVer ASAP.

**Comment by RX14** [comment]
We are using semver. We just haven't released yet.

**Comment by Kubuxu** [comment]
I know we are using SemVer but at the same type we are in null zone. We need to reflect breaking changes in at least in Minor version.

**Comment by RX14** [comment]
Once we release 0.1.0 this should start. Once 0.2.0 breaking changes should be a minor increase, with patch releases for bug fixes and additions.
